//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par xsd, Version=4.6.1055.0.
// 
namespace ToolKit {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Level : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LevelVictoryConditionsVictoryCondition[] victoryConditionsField;
        
        private LevelContent contentField;
        
        private LevelTilesTile[] tilesField;
        
        private string nameField;
        
        private string rowsField;
        
        private string columnsField;
        
        private string nextLevelField;

		private string startPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VictoryCondition", typeof(LevelVictoryConditionsVictoryCondition), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public LevelVictoryConditionsVictoryCondition[] VictoryConditions {
            get {
                return this.victoryConditionsField;
            }
            set {
                this.victoryConditionsField = value;
                this.RaisePropertyChanged("VictoryConditions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelContent Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Tile", typeof(LevelTilesTile), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public LevelTilesTile[] Tiles {
            get {
                return this.tilesField;
            }
            set {
                this.tilesField = value;
                this.RaisePropertyChanged("Tiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("rows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextLevel {
            get {
                return this.nextLevelField;
            }
            set {
                this.nextLevelField = value;
                this.RaisePropertyChanged("nextLevel");
            }
        }

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string startPosition
		{
			get
			{
				return this.startPositionField;
			}
			set
			{
				this.startPositionField = value;
				this.RaisePropertyChanged("startPosition");
				this.RaisePropertyChanged("Level");
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelVictoryConditionsVictoryCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classField;
        
        private string assetNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
                this.RaisePropertyChanged("assetName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LevelContentTextureRessource[] textureRessourceField;
        
        private LevelContentSoundRessource[] soundRessourceField;
        
        private LevelContentBackgroundMusic[] backgroundMusicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TextureRessource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelContentTextureRessource[] TextureRessource {
            get {
                return this.textureRessourceField;
            }
            set {
                this.textureRessourceField = value;
                this.RaisePropertyChanged("TextureRessource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoundRessource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelContentSoundRessource[] SoundRessource {
            get {
                return this.soundRessourceField;
            }
            set {
                this.soundRessourceField = value;
                this.RaisePropertyChanged("SoundRessource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BackgroundMusic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelContentBackgroundMusic[] BackgroundMusic {
            get {
                return this.backgroundMusicField;
            }
            set {
                this.backgroundMusicField = value;
                this.RaisePropertyChanged("BackgroundMusic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelContentTextureRessource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelContentSoundRessource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelContentBackgroundMusic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTilesTile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LevelTilesTileLayer[] layerField;
        
        private LevelTilesTileActor[] actorField;
        
        private string posXField;
        
        private string posYField;
        
        private string isWalkableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Layer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTilesTileLayer[] Layer {
            get {
                return this.layerField;
            }
            set {
                this.layerField = value;
                this.RaisePropertyChanged("Layer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Actor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTilesTileActor[] Actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
                this.RaisePropertyChanged("Actor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string posX {
            get {
                return this.posXField;
            }
            set {
                this.posXField = value;
                this.RaisePropertyChanged("posX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string posY {
            get {
                return this.posYField;
            }
            set {
                this.posYField = value;
                this.RaisePropertyChanged("posY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isWalkable {
            get {
                return this.isWalkableField;
            }
            set {
                this.isWalkableField = value;
                this.RaisePropertyChanged("isWalkable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTilesTileLayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string assetNameField;
        
        private string depthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
                this.RaisePropertyChanged("assetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
                this.RaisePropertyChanged("depth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTilesTileActor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LevelTilesTileActorMover moverField;
        
        private string classField;
        
        private string assetNameField;
        
        private string pickupSoundField;
        
        private string healthValueField;
        
        private string scoreValueField;
        
        private string lightScaleField;
        
        private string defenseValueField;
        
        private string attackValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mover", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTilesTileActorMover Mover {
            get {
                return this.moverField;
            }
            set {
                this.moverField = value;
                this.RaisePropertyChanged("Mover");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
                this.RaisePropertyChanged("assetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pickupSound {
            get {
                return this.pickupSoundField;
            }
            set {
                this.pickupSoundField = value;
                this.RaisePropertyChanged("pickupSound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string healthValue {
            get {
                return this.healthValueField;
            }
            set {
                this.healthValueField = value;
                this.RaisePropertyChanged("healthValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scoreValue {
            get {
                return this.scoreValueField;
            }
            set {
                this.scoreValueField = value;
                this.RaisePropertyChanged("scoreValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lightScale {
            get {
                return this.lightScaleField;
            }
            set {
                this.lightScaleField = value;
                this.RaisePropertyChanged("lightScale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string defenseValue {
            get {
                return this.defenseValueField;
            }
            set {
                this.defenseValueField = value;
                this.RaisePropertyChanged("defenseValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attackValue {
            get {
                return this.attackValueField;
            }
            set {
                this.attackValueField = value;
                this.RaisePropertyChanged("attackValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTilesTileActorMover : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classField;
        
        private string moveSpeedField;
        
        private string intervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string moveSpeed {
            get {
                return this.moveSpeedField;
            }
            set {
                this.moveSpeedField = value;
                this.RaisePropertyChanged("moveSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
                this.RaisePropertyChanged("interval");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Level itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Level")]
        public Level Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
